# https://stackoverflow.com/a/68213855/16484891
# CC BY-SA 4.0

name: Sync main repo
run-name: Auto update virus-bar-group/virus-bar-group.github.io submodule themes/pure

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: virus-bar-group/virus-bar-group.github.io
          ref: "master"
          token: ${{ secrets.ACTIONS_SYNC_MAIN_REPO }}
          submodules: true

      - name: setup git config
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: update submodules
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote

      - name: commit
        run: |
          git add --all
          git commit -m "theme: auto sync virus-bar-group/hexo-theme-pure"
          git push
